var mainObj = {
    squad: [
      "Barack Lesnar",
      "Bethany Davey",
      "Bridjet Jacqueline",
      "Bronwyn Mroczkowski",
      "J.D. Lowe",
      "James Russell",
      "Jennifer Morrison",
      "Marisa Lally",
    ],
    setValues: true,
    defaultShowLength: 1080,
    defaultMinGap: 30,
    defaultMaxGap: 120,
    intro: `Hello. I am The Babysitter. The players you see before you are the Smart Babies. This is an experiment. merging technology and improvisation. Randomly. the babies will be interrupted by me, and I will tell them to change the game. Or. else. Aside from this introduction. everything else is absolutely unplanned and improvised.`,
    prompts: {
      startItOff: [
        `What's your favorite word.`,
        `What's your favorite food?`,
        `What's your favorite movie?`,
        `What's a gift you DON'T want on your birthday?`,
        `Name something that is NOT green.`,
        `What's your favorite word that starts with the letter $alph?`,
      ],
      audience: [
        `What do you think of when you think of summer?`,
        `Name a celebrity who is alive. The person who just spoke now has to do an impression of them.`,
        `Shout out a word you think of when you think school.`,
        `What is something you have at your workplace that is uncommon?`,
        `What is something you have in your garage right now?`,
        `Name a European country, and the players have to talk in that accent.`,
      ],
      preprogrammed: [
        `Rotate characters!`,
        `Increase your physicality.`,
        `Confess your undying love.`,
        `Talk about your biggest fear.`,
        `Make an offer they can't refuse.`,
        `Someone on stage has a hidden motive. Reveal it.`,
        `Whatever you are feeling right now, increase it.`,
        `Until the end of the scene, you must speak in rhyme.`,
        `Everyone freeze! Stay perfectly still until the end of the scene`,
        `Whoever is off stage are now the directors of this scene.`,
        `Speak in only three word sentences.`,
        `Time warp! Let's see this scene $timeWarp in the future.`,
        `You hear in the distance: $sound.`,
        `$player must now come on stage and play a brand new character.`,
        `Everyone is suddenly filled with the emotion: $emotion.`,
        `You can only speak when touching another baby.`,
        `Style change: Continue the scene in the style of $style.`,
`Another baby, join the stage as a new character.`,
      ],
      //audiencePercent: 0.69,
      audiencePercent: 0,
    },
    wrapup: `Alright, it's one more minute until playtime is through!`,
    ending: `That's the show, thank you so much for joining us, we are Smart Babies! Have a good night!`,
    timeWarps: [
      `five minutes`,
      `a day`,
      `a year`,
      `three years`,
    ],
    styles: [
      `Documentary`,
      `Horror`,
      `Romantic Comedy`,
      `Shakespearean`,
      `Wild West`,
      `Film Noir`,
      `Science Fiction`,
      `Superhero Movie`,
      `Coming Of Age`,
      `Fantasy`,
      `Buddy Cop`,
      `Soap Opera`,
      `Sitcom`,
      `Educational Children Programming`,
      `Silent Film`,
      `Elementary School Play`,
      `Disaster`,
      `Period Drama`,
      `Police Procedural`,
      `Cooking Show`,
      `Reality Show`,
      `Game Show`,
    ],
    sounds:[
      `an explosion`,
      `police sirens`,
      `a wolf howling`,
      `a baby crying`,
      `a tornado siren`,
    ],
    emotions:[
      `Frightened`,
      `Helpless`,
      `Panicked`,
      `Hysterical`,
      `Inferior`,
      `Inadequate`,
      `Worried`,
      `Anxious`,
      `Mortified`,
      `Dreadful`,
      `Hateful`,
      `Hostile`,
      `Agitated`,
      `Frustrated`,
      `Annoyed`,
      `Aggravated`,
      `Resentful`,
      `Jealous`,
      `Contemptuous`,
      `Revolted`,
      `Agonized`,
      `Hurt`,
      `Depressed`,
      `Sorrowful`,
      `Dismayed`,
      `Displeased`,
      `Regretful`,
      `Guilty`,
      `Isolated`,
      `Lonely`,
      `Anguished`,
      `Powerless`,
      `Shocked`,
      `Dismayed`,
      `Disillusioned`,
      `Perplexed`,
      `Astonished`,
      `Awe-struck`,
      `Speechless`,
      `Astounded`,
      `Stimulated`,
      `Touched`,
      `Thankful`,
      `Pleased`,
      `Amused`,
      `Delighted`,
      `Jovial`,
      `Playful`,
      `Triumphant`,
      `Illustrious`,
      `Eager`,
      `Hopeful`,
      `Excited`,
      `Zealous`,
      `Euphoric`,
      `Jubilant`,
      `Enchanted`,
      `Rapturous`,
      `Passionate`,
      `Infatuated`,
      `Attractive`,
      `Enamored`,
      `Sentimental`,
      `Affectionate`,
      `Caring`,
      `Compassionate`,
      `Tranquil`,
      `Satisfied`,
      `Scared`,
      `Terrified`,
      `Insecure`,
      `Nervous`,
      `Horrified`,
      `Enraged`,
      `Exasperated`,
      `Irritable`,
      `Envious`,
      `Disgusted`,
      `Distressed`,
      `Melancholic`,
      `Disappointed`,
      `Shameful`,
      `Neglected`,
      `Hopeless`,
      `Stunned`,
      `Confused`,
      `Amazed`,
      `Overcome`,
      `Moved`,
      `Content`,
      `Happy`,
      `Cheerful`,
      `Proud`,
      `Optimistic`,
      `Enthusiastic`,
      `Elated`,
      `Enthralled`,
      `Desirous`,
      `Romantic`,
      `Longing`,
      `Tender`,
      `Peaceful`
    ],
  }